name: mitoflex
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.6.10
  - megahit=1.2.9
  - psutil=5.7.0
  - wise2=2.4.1
  - hmmer=3.2.1
  - circos=0.69.8
  - bwa=0.7.17
  - samtools=1.3.1
  - infernal=1.1.2
  - blast=2.5.0
  - pandas=1.0.3
  - ete3=3.1.1
  - biopython=1.76
